### ISSUE TITLE
need autoconf before install openmpi

### ISSUE THREAD

**Issue by liuqc0419** [jam31118/rigged-qprop#11]
The installation of openmpi is failed because the lack of autoconf, you`d better check if autoconf is installed in the install-openmpi.sh before the main installation.

**Comment by jam31118** [comment]
Sometimes, there arise an error complaining that some tools such as `autoconf`, `make` and possibly `gcc` or `g++`. In order to make the installation script more stable, it should be checked whether all those required tools are ready.

**Comment by jam31118** [comment]
Fixed at b95d3ef.

Guide on installing build tools had been added to [wiki page](https://github.com/jam31118/rigged-qprop/wiki/Installation).
